### PR TITLE
Clawshot redo

### PR DESCRIPTION
**Pull request by DS-Minetest**

### CODE REVIEW

**Comment by DS-Minetest** [comment]
Heh, you should have squashed them.
(Also because of this there's now a cat in commits. :3)

**Comment by tobyplowy** [comment]
@DS-Minetest thanks for your contribution to the project​ :3

**Comment by tobyplowy** [comment]
@DS-Minetest the game seems to crash if you use the clawshot

**Comment by DS-Minetest** [comment]
> crash

Your old MT version causes that.

Btw. the claw entity could easily be oriented 3d in the direction (not as now only horizontal) if there was a bone, but I didn't find the `.blend` file. @D00Med

**Pull request merged**
