### PR TITLE
Make the Wood Framed Glass connect, and fix issue 133.

### PR DESCRIPTION
**Pull request by kingoscargames**

### CODE REVIEW

**Comment by tobyplowy** [comment]
@kingoscargames thanks for the fix ;D

please try to keep the fixes in separit prs

**Comment by kingoscargames** [comment]
> please try to keep the fixes in separit prs
I know but i messed it up, so i just renamed it XD

**Comment by DS-Minetest** [comment]
@kingoscargames 
Github has keywords, if an issue should be closed after the PR is merged, write something like "Fixes #\<issuenumber>." or "Closes #\<issuenumber>." into the first comment. The one who merges the PR will automatically also close the issue. But writing it into the title doesn't work.

**Comment by kingoscargames** [comment]
Oh, ok.

**Pull request merged**
