### PR TITLE
Fix "Dead Grass drops unknown node" .

### PR DESCRIPTION
**Pull request by kingoscargames**
https://github.com/D00Med/farlands/issues/156

### CODE REVIEW

**Comment by kingoscargames** [comment]
oops
 i messed up 
image

**Comment by kingoscargames** [comment]
edit: nevermind

**Comment by MarkuBu** [comment]
Fixed this in the 0.5 port

**Comment by tobyplowy** [comment]
@MarkuBu so this can be closed?
Also Close https://github.com/D00Med/farlands/issues/156 ?

**Comment by MarkuBu** [comment]
Should be closed if it is fixed in 1.1

**Comment by D00Med** [comment]
So does this get merged or no?

**Pull request merged**
