### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by NewbProgrammer101**
Typo fix

### CODE REVIEW

**Comment by tobyplowy** [comment]
@D00Med there seems to be some conflicts I can't marge

**Comment by NewbProgrammer101** [comment]
I fixed the issue. You can merge it now. :)

**Comment by NewbProgrammer101** [comment]
Fixed other description errors.

**Comment by NewbProgrammer101** [comment]
Wait... I noticed I messed up the paintings list... hold on. Will fix.

**Comment by NewbProgrammer101** [comment]
Now it's fixed.

**Comment by tobyplowy** [comment]
@NewbProgrammer101 thanks

**Pull request merged**
