### PR TITLE
Fix the weird look of the "straw slab" and "straw stair"

### PR DESCRIPTION
**Pull request by kingoscargames**
https://github.com/D00Med/farlands/issues/144

### CODE REVIEW

**Comment by MarkuBu** [comment]
Maybe we should wait before we merge this because

1. we will make major changes to the repository
2. as far as I know there is a pull request that fixes the textures on stairs and other nodes in general. Textures should align along the world coordinate. But I can't find the issue/PC now

**Comment by MarkuBu** [comment]
Ok, it's a simple change, but we should check this first with other texture packs

**Comment by tobyplowy** [comment]
@MarkuBu the straw top texture was added by me it's not in default or other texturepacks

**Comment by MarkuBu** [comment]
@tobyplowy I know, that's the problem. With this change you may have problems if you want to use different texture packs. If people want to play with their favorite TP they can have strange looking nodes.

**Comment by MarkuBu** [comment]
Oh, and another point is, that it is a change in the stairs mod. This could be done after the registration with override_item()

**Comment by tobyplowy** [comment]
> @tobyplowy I know, that's the problem. With this change you may have problems if you want to use different texture packs. If people want to play with their favorite TP they can have strange looking nodes.

I don't care about that they should just update it (it's not alot of work just rename a texture form the Minecraft pack and put it in the Mt pack)

**Comment by MarkuBu** [comment]
Maybe we should open an issue in MTG

**Comment by tobyplowy** [comment]
You already have xD

**Comment by kingoscargames** [comment]
What do you mean?

**Pull request closed without merging**
